# Matugen generated colors
$background = rgb(1a1111)
$foreground = rgb(f1dedd)
$surface = rgb(1a1111)
$surface_bright = rgb(423736)
$surface_container = rgb(271d1d)
$on_surface = rgb(f1dedd)

$primary = rgb(ffb3ae)
$on_primary = rgb(571e1c)
$primary_container = rgb(733330)

$secondary = rgb(e7bdb9)
$tertiary = rgb(e2c28c)
$error = rgb(ffb4ab)

# Use these in hyprland config
$active_border = $primary
$inactive_border = $surface_container
