# Matugen generated colors
$background = rgb(111318)
$foreground = rgb(e1e2e9)
$surface = rgb(111318)
$surface_bright = rgb(37393e)
$surface_container = rgb(1d2024)
$on_surface = rgb(e1e2e9)

$primary = rgb(a5c8fe)
$on_primary = rgb(00315d)
$primary_container = rgb(214876)

$secondary = rgb(bcc7dc)
$tertiary = rgb(d9bde3)
$error = rgb(ffb4ab)

# Use these in hyprland config
$active_border = $primary
$inactive_border = $surface_container
