# ================================
# ========== Variables ===========
# ================================
$mainMod = SUPER

# ================================
# ========== Sources =============
# ================================
source = ~/.config/hypr/keybinds/apps.conf
source = ~/.config/hypr/keybinds/navigation.conf
source = ~/.config/hypr/keybinds/media.conf
