set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g history-limit 50000
set -g default-termina "tmux-256color"

setw -g mode-keys vi
set -g status-keys vi

unbind f
bind-key f display-popup -E -w 80% -h 60% "/home/solyshi/scripts/tmux-sessionizer"
