$background = rgb(12140e)
$foreground = rgb(e2e3d8)
$surface = rgb(1e201a)
$primary = rgb(b1d18a)
$primary_container = rgb(344e16)
$on_primary = rgb(1f3701)
$secondary = rgb(bfcbad)
$secondary_container = rgb(404a33)
$tertiary = rgb(a0d0cc)
$error = rgb(ffb4ab)
$active_border = rgb(b1d18a)
$inactive_border = rgb(1e201a)
