# --- Matugen Terminal Colors ---

# Grundfarben
foreground            #dfe3e7
background            #0f1417
selection_foreground  #003547
selection_background  #8ccff1

# Cursor
cursor                #8ccff1
cursor_text_color     #003547

# URL Farbe (passend zum Akzent)
url_color             #8ccff1

# Border (Fensterränder in Kitty)
active_border_color   #8ccff1
inactive_border_color #8a9297
bell_border_color     #ffb4ab

# Tab bar - Passend zum Waybar Design
tab_bar_style               fade
tab_fade                    1
active_tab_foreground       #003547
active_tab_background       #8ccff1
active_tab_font_style       bold
inactive_tab_foreground     #c0c7cd
inactive_tab_background     #171c1f
inactive_tab_font_style     normal
tab_bar_background          #0f1417

# --- ANSI Colors (Für CLI Tools wie btop, lsd, etc.) ---

# Black (Dunkelster Untergrund)
color0  #0a0f12
color8  #353a3d

# Red (Fehler/Warnungen)
color1  #ffb4ab
color9  #93000a

# Green (Erfolg/Strings)
color2  #c7c2ea
color10 #c7c2ea

# Yellow (Warnungen/Typen)
color3  #b4cad6
color11 #b4cad6

# Blue (Akzent/Keywords)
color4  #8ccff1
color12 #8ccff1

# Magenta
color5  #004d66
color13 #c0e8ff

# Cyan
color6  #364954
color14 #d0e6f3

# White (Textfarben)
color7  #c0c7cd
color15 #dfe3e7
