# --- Matugen Terminal Colors ---

# Grundfarben
foreground            #ece1d4
background            #18130b
selection_foreground  #432c00
selection_background  #f0be6d

# Cursor
cursor                #f0be6d
cursor_text_color     #432c00

# URL Farbe (passend zum Akzent)
url_color             #f0be6d

# Border (Fensterränder in Kitty)
active_border_color   #f0be6d
inactive_border_color #9b8f80
bell_border_color     #ffb4ab

# Tab bar - Passend zum Waybar Design
tab_bar_style               fade
tab_fade                    1
active_tab_foreground       #432c00
active_tab_background       #f0be6d
active_tab_font_style       bold
inactive_tab_foreground     #d2c4b4
inactive_tab_background     #201b13
inactive_tab_font_style     normal
tab_bar_background          #18130b

# --- ANSI Colors (Für CLI Tools wie btop, lsd, etc.) ---

# Black (Dunkelster Untergrund)
color0  #120d07
color8  #3f382f

# Red (Fehler/Warnungen)
color1  #ffb4ab
color9  #93000a

# Green (Erfolg/Strings)
color2  #b5cea4
color10 #b5cea4

# Yellow (Warnungen/Typen)
color3  #dbc3a1
color11 #dbc3a1

# Blue (Akzent/Keywords)
color4  #f0be6d
color12 #f0be6d

# Magenta
color5  #604100
color13 #ffdead

# Cyan
color6  #55442a
color14 #f8dfbb

# White (Textfarben)
color7  #d2c4b4
color15 #ece1d4
