# Matugen generated colors
foreground #f1dedd
background #1a1111
selection_foreground #571e1c
selection_background #ffb3ae

# Cursor
cursor #ffb3ae
cursor_text_color #571e1c

# Black
color0 #1a1111
color8 #423736

# Red
color1 #ffb4ab
color9 #ffb4ab

# Green
color2 #e2c28c
color10 #e2c28c

# Yellow
color3 #e7bdb9
color11 #e7bdb9

# Blue
color4 #ffb3ae
color12 #ffb3ae

# Magenta
color5 #594319
color13 #e2c28c

# Cyan
color6 #5d3f3d
color14 #e7bdb9

# White
color7 #f1dedd
color15 #f1dedd

# Tab bar
tab_bar_background #1a1111
active_tab_foreground #571e1c
active_tab_background #ffb3ae
inactive_tab_foreground #f1dedd
inactive_tab_background #271d1d
