# ==============================================================================
# Fonts
# ==============================================================================
# BEGIN_KITTY_FONTS
font_family      family="Fira Code"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 11.0
disable_ligatures never

# ==============================================================================
# Window
# ==============================================================================
window_padding_width 8
placement_strategy center
background_opacity 0.70
background_blur 1
hide_window_decorations yes

# ==============================================================================
# Colors (matugen generated)
# ==============================================================================
include colors.conf

# ==============================================================================
# Cursor
# ==============================================================================
cursor_shape beam
cursor_blink_interval 0

# ==============================================================================
# Scrollback
# ==============================================================================
scrollback_lines 10000

# ==============================================================================
# Bell
# ==============================================================================
enable_audio_bell no

# ==============================================================================
# Remote Control
# ==============================================================================
allow_remote_control yes
listen_on unix:/tmp/kitty
watcher yes



